### ISSUE TITLE
GroupConsumer inits successfully with invalid host and will not end

### ISSUE THREAD

**Issue by Mattenable** [oleksiyk/kafka#104]
See https://github.com/Mattenable/no-kafka-test

Can you help me figure out what I'm doing wrong? I'd like the connection attempts to stop.

First issue is I would expect consumer init to fail, but goes to then instead of catch. 

Also end function does not stop meta data refresh. Here's the the output I get (the NoKafkaConnectionError will continue forever):

```
STARTING
2016-08-09T02:00:15.927Z ERROR no-kafka-client Metadata request failed: NoKafkaConnectionError [invalidhost:9092]: Error: getaddrinfo ENOTFOUND invalidhost invalidhost:9092
{ [NoKafkaConnectionError: Error: getaddrinfo ENOTFOUND invalidhost invalidhost:9092]
  name: 'NoKafkaConnectionError',
  server: 'invalidhost:9092',
  message: 'Error: getaddrinfo ENOTFOUND invalidhost invalidhost:9092' } 
[at apply (/Users/mnehrbass/projects/_playground/no-kafka-test/node_modules/no-kafka/node_modules/lodash/lodash.js:445:27)]
FAILED, NO ERROR THROWN
Unhandled rejection NoKafkaConnectionError [invalidhost:9092]: Error: getaddrinfo ENOTFOUND invalidhost invalidhost:9092

2016-08-09T02:00:16.932Z ERROR no-kafka-client Metadata request failed: NoKafkaConnectionError [invalidhost:9092]: Error: getaddrinfo ENOTFOUND invalidhost invalidhost:9092
{ [NoKafkaConnectionError: Error: getaddrinfo ENOTFOUND invalidhost invalidhost:9092]
  name: 'NoKafkaConnectionError',
  server: 'invalidhost:9092',
  message: 'Error: getaddrinfo ENOTFOUND invalidhost invalidhost:9092' } 
[at apply (/Users/mnehrbass/projects/_playground/no-kafka-test/node_modules/no-kafka/node_modules/lodash/lodash.js:445:27)]
```

**Comment by oleksiyk** [comment]
Related to #73
