### ISSUE TITLE
Full Rejoin attempt failed.

### ISSUE THREAD

**Issue by raviten** [oleksiyk/kafka#156]
Can you please throw some info on this issue. We are facing problem with producers.

Error on no-kafka
`
2017-03-05T11:04:20.442Z ERROR no-kafka-client Metadata request failed: NoKafkaConnectionError [localhost:9092]: Error: connect ECONNREFUSED 127.0.0.1:9092
{ [NoKafkaConnectionError: Error: connect ECONNREFUSED 127.0.0.1:9092]
  name: 'NoKafkaConnectionError',
  server: 'localhost:9092',
  message: 'Error: connect ECONNREFUSED 127.0.0.1:9092' } 
`

Error on kafka server side
```
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'group_protocols': Error reading field 'protocol_name': java.lang.NegativeArraySizeException
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:71)
	at org.apache.kafka.common.protocol.ProtoUtils.parseRequest(ProtoUtils.java:60)
	at org.apache.kafka.common.requests.JoinGroupRequest.parse(JoinGroupRequest.java:144)
	at org.apache.kafka.common.requests.AbstractRequest.getRequest(AbstractRequest.java:55)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:79)
	at kafka.network.Processor$$anonfun$run$11.apply(SocketServer.scala:426)
	at kafka.network.Processor$$anonfun$run$11.apply(SocketServer.scala:421)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at kafka.network.Processor.run(SocketServer.scala:421)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by oleksiyk** [comment]
I don't think thats producers, thats clearly group consumers.
