### ISSUE TITLE
wrong tag

### ISSUE THREAD

**Issue by maturanafp** [oleksiyk/kafka#186]
I use this function to connect to Kafka server:

var producer = new Kafka.Producer({
    connectionString: 'kafka://'+ ipAddress + ':' + port,
    ssl: {
		cert: fs.readFileSync('c:\\Temp\\180008.cer').toString('utf-8'),
		key: fs.readFileSync('c:\\Temp\\180008.key').toString('utf-8')
	  }
	});

The certificate and the key are correctly generated and signed by our CA.  I get the below error when trying to connect.  Can you please provide some insight about what could be wrong with is connection. I ran node from a windows 7 box.  Thank you.    

2017-07-05T21:06:26.345Z ERROR no-kafka-client Metadata request failed: Error: e
rror:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag
Error: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag
    at Error (native)
    at Object.createSecureContext (_tls_common.js:90:19)
    at Object.exports.connect (_tls_wrap.js:1020:48)
    at C:\Users\maturana\Desktop\CoE\Twinsburg data\Pilot\Phase II - Production\
kafkaconnector\kafka test\kafka-test\node_modules\no-kafka\lib\connection.js:71:
35
    at Promise.cancellationExecute [as _execute] (C:\Users\maturana\Desktop\CoE\
Twinsburg data\Pilot\Phase II - Production\kafkaconnector\kafka test\kafka-test\
node_modules\bluebird\js\release\debuggability.js:321:9)
    at Promise._resolveFromExecutor (C:\Users\maturana\Desktop\CoE\Twinsburg dat
a\Pilot\Phase II - Production\kafkaconnector\kafka test\kafka-test\node_modules\
bluebird\js\release\promise.js:483:18)
    at new Promise (C:\Users\maturana\Desktop\CoE\Twinsburg data\Pilot\Phase II
- Production\kafkaconnector\kafka test\kafka-test\node_modules\bluebird\js\relea
se\promise.js:79:10)
    at Connection.connect (C:\Users\maturana\Desktop\CoE\Twinsburg data\Pilot\Ph
ase II - Production\kafkaconnector\kafka test\kafka-test\node_modules\no-kafka\l
ib\connection.js:54:9)
    at Connection.send (C:\Users\maturana\Desktop\CoE\Twinsburg data\Pilot\Phase
 II - Production\kafkaconnector\kafka test\kafka-test\node_modules\no-kafka\lib\
connection.js:154:21)
    at C:\Users\maturana\Desktop\CoE\Twinsburg data\Pilot\Phase II - Production\
kafkaconnector\kafka test\kafka-test\node_modules\no-kafka\lib\client.js:285:27
    at Array.map (native)
    at Client.metadataRequest (C:\Users\maturana\Desktop\CoE\Twinsburg data\Pilo
t\Phase II - Production\kafkaconnector\kafka test\kafka-test\node_modules\no-kaf
ka\lib\client.js:284:44)
    at _try (C:\Users\maturana\Desktop\CoE\Twinsburg data\Pilot\Phase II - Produ
ction\kafkaconnector\kafka test\kafka-test\node_modules\no-kafka\lib\client.js:2
25:21)
    at Client.updateMetadata (C:\Users\maturana\Desktop\CoE\Twinsburg data\Pilot
\Phase II - Production\kafkaconnector\kafka test\kafka-test\node_modules\no-kafk
a\lib\client.js:260:6)
    at C:\Users\maturana\Desktop\CoE\Twinsburg data\Pilot\Phase II - Production\
kafkaconnector\kafka test\kafka-test\node_modules\no-kafka\lib\client.js:128:21
    at tryCatcher (C:\Users\maturana\Desktop\CoE\Twinsburg data\Pilot\Phase II -
 Production\kafkaconnector\kafka test\kafka-test\node_modules\bluebird\js\releas
e\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\maturana\Desktop\CoE\Twinsbur
g data\Pilot\Phase II - Production\kafkaconnector\kafka test\kafka-test\node_mod
ules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\maturana\Desktop\CoE\Twinsburg data\Pilo
t\Phase II - Production\kafkaconnector\kafka test\kafka-test\node_modules\bluebi
rd\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\maturana\Desktop\CoE\Twinsburg data\Pil
ot\Phase II - Production\kafkaconnector\kafka test\kafka-test\node_modules\blueb
ird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\maturana\Desktop\CoE\Twinsburg data\Pil
ot\Phase II - Production\kafkaconnector\kafka test\kafka-test\node_modules\blueb
ird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\maturana\Desktop\CoE\Twinsburg data\Pilot\Pha
se II - Production\kafkaconnector\kafka test\kafka-test\node_modules\bluebird\js
\release\async.js:133:16)
    at Async._drainQueues (C:\Users\maturana\Desktop\CoE\Twinsburg data\Pilot\Ph
ase II - Production\kafkaconnector\kafka test\kafka-test\node_modules\bluebird\j
s\release\async.js:143:10)

**Comment by oleksiyk** [comment]
I think your certificate is not in PEM format or has trailing spaces, broken formatting, etc.
