### ISSUE TITLE
Payload length mismatch on the producer side 

### ISSUE THREAD

**Issue by kroyhpe** [oleksiyk/kafka#214]
This is relation to the earlier issue I have raised that the Consumer is not able to read  ( #207 ) specific messages.

Further Troubleshooting and analysis  of the topic segment file produced the following results
1) Kafka Open Source Utility ( kafka.tools.DumpLogSegments) and Open Source Kafka Console Consumer ( Jave ) would fail to read a message in a specific offset . Both will fail with the following error: 

org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition XYZTopic-1 at offset 606508
Caused by: java.lang.IllegalArgumentException
        at java.nio.Buffer.limit(Buffer.java:275)
        at org.apache.kafka.common.utils.Utils.sizeDelimited(Utils.java:791)
        at org.apache.kafka.common.record.Record.value(Record.java:268)
        at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:867)
        at org.apache.kafka.clients.consumer.internals.Fetcher.parseCompletedFetch(Fetcher.java:775)
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:473)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1062)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:995)
        at kafka.consumer.NewShinyConsumer.receive(BaseConsumer.scala:88)
        at kafka.tools.ConsoleConsumer$.process(ConsoleConsumer.scala:120)
        at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:75)
        at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:50)
        at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)

2) On analysis of Kafka console consumer java code this points to In ByteBuffer

 public final Buffer limit(int newLimit) {
        if ((newLimit > capacity) || (newLimit < 0))
            throw new IllegalArgumentException();

 Based on the analysis this points to Root cause that  while constructing the payload, in the producer side, size of the payload [4 byte payload length, containing length V] is not matching (>) the size of actual  payload. We are referring to the payload structure as provided by the Kafka Low Level API that no-kafka must be creating to implement the low level Kafka API

* A message. The format of an N byte message is the following:
 *
 * 1. 4 byte CRC32 of the message
 * 2. 1 byte "magic" identifier to allow format changes, value is 0 or 1
 * 3. 1 byte "attributes" identifier to allow annotations on the message independent of the version
 *    bit 0 ~ 2 : Compression codec.
 *      0 : no compression
 *      1 : gzip
 *      2 : snappy
 *      3 : lz4
 *    bit 3 : Timestamp type
 *      0 : create time
 *      1 : log append time
 *    bit 4 ~ 7 : reserved
 * 4. (Optional) 8 byte timestamp only if "magic" identifier is greater than 0
 
 //Actual key, value data
 * 5. 4 byte key length, containing length K
 * 6. K byte key
 * 7. 4 byte payload length, containing length V  995
 * 8. V byte payload [buffer 995 but actual less ]

3) Since we are using the no-kafka on the Producer side we want to understand if there can be network hitch etc  etc which can be causing this rare behavior on couple of messages in a 400 messages per minute throughput topic - which is not very high for Kafka.

**Comment by oleksiyk** [comment]
My suggestion is to look at message value `Buffer` object that you pass to no-kafka producer, it is possible that Buffer.length doesn't match real buffer length, e.g. you modify the value's buffer object right after you called `producer.send()` but before it was serialised. Make a copy with `Buffer.copy`.
