### ISSUE TITLE
RangeError: index out of range

### ISSUE THREAD

**Issue by memelet** [oleksiyk/kafka#75]
We are getting this error. We don't know why. There is none of our code in the stack trace. Has anybody seen this before?

```
Collector halted, process exiting [RangeError: index out of range] RangeError: index out of range
  at checkInt (buffer.js:831:11)
  at Buffer.writeInt32BE (buffer.js:1022:5)
  at _Writer.define.write (/opt/vi-node/node_modules/no-kafka/node_modules/bin-protocol/lib/index.js:142:21)
  at _Writer._write (/opt/vi-node/node_modules/no-kafka/node_modules/bin-protocol/lib/writer.js:28:8)
  at apply (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:410:27)
  at _Writer.wrapper (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:4837:16)
  at _Writer.Protocol.define.write (/opt/vi-node/node_modules/no-kafka/lib/protocol/common.js:98:14)
  at _Writer._write (/opt/vi-node/node_modules/no-kafka/node_modules/bin-protocol/lib/writer.js:28:8)
  at apply (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:410:27)
  at _Writer.wrapper [as KafkaOffset] (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:4837:16)
  at _Writer.Protocol.define.write (/opt/vi-node/node_modules/no-kafka/lib/protocol/common.js:175:14)
  at _Writer._write (/opt/vi-node/node_modules/no-kafka/node_modules/bin-protocol/lib/writer.js:28:8)
  at apply (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:411:27)
  at _Writer.wrapper [as MessageSetItem] (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:4837:16)
  at _Writer.Writer.loop (/opt/vi-node/node_modules/no-kafka/node_modules/bin-protocol/lib/writer.js:78:12)
  at _Writer.Protocol.define.write (/opt/vi-node/node_modules/no-kafka/lib/protocol/common.js:200:14)
  at _Writer._write (/opt/vi-node/node_modules/no-kafka/node_modules/bin-protocol/lib/writer.js:28:8)
  at apply (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:410:27)
  at _Writer.wrapper [as MessageSet] (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:4837:16)
  at _Writer.Protocol.define.write (/opt/vi-node/node_modules/no-kafka/lib/protocol/produce.js:19:14)
  at _Writer._write (/opt/vi-node/node_modules/no-kafka/node_modules/bin-protocol/lib/writer.js:28:8)
  at apply (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:411:27)
  at _Writer.wrapper [as ProduceRequestPartitionItem] (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:4837:16)
  at _Writer.Writer.loop (/opt/vi-node/node_modules/no-kafka/node_modules/bin-protocol/lib/writer.js:78:12)
  at _Writer.Protocol.define.write (/opt/vi-node/node_modules/no-kafka/lib/protocol/common.js:78:18)
  at _Writer._write (/opt/vi-node/node_modules/no-kafka/node_modules/bin-protocol/lib/writer.js:28:8)
  at apply (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:411:27)
  at _Writer.wrapper [as array] (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:4837:16)
  at _Writer.Protocol.define.write (/opt/vi-node/node_modules/no-kafka/lib/protocol/produce.js:31:14)
  at _Writer._write (/opt/vi-node/node_modules/no-kafka/node_modules/bin-protocol/lib/writer.js:28:8)
  at apply (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:411:27)
  at _Writer.wrapper [as ProduceRequestTopicItem] (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:4837:16)
  at _Writer.Writer.loop (/opt/vi-node/node_modules/no-kafka/node_modules/bin-protocol/lib/writer.js:78:12)
  at _Writer.Protocol.define.write (/opt/vi-node/node_modules/no-kafka/lib/protocol/common.js:78:18)
  at _Writer._write (/opt/vi-node/node_modules/no-kafka/node_modules/bin-protocol/lib/writer.js:28:8)
  at apply (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:411:27)
  at _Writer.wrapper [as array] (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:4837:16)
  at _Writer.Protocol.define.write (/opt/vi-node/node_modules/no-kafka/lib/protocol/produce.js:46:14)
  at _Writer._write (/opt/vi-node/node_modules/no-kafka/node_modules/bin-protocol/lib/writer.js:28:8)
  at apply (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:410:27)
  at _Writer.wrapper [as ProduceRequest] (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:4837:16)
  at /opt/vi-node/node_modules/no-kafka/lib/client.js:286:52
  at /opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:3116:27
  at /opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:4411:15
  at baseForOwn (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:2654:24)
  at /opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:4380:18
  at baseMap (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:3115:7)
  at Function.map (/opt/vi-node/node_modules/no-kafka/node_modules/lodash/lodash.js:8851:14)
  at /opt/vi-node/node_modules/no-kafka/lib/client.js:285:34
  at tryCatcher (/opt/vi-node/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/opt/vi-node/node_modules/bluebird/js/release/promise.js:502:31)
  at Promise._settlePromise (/opt/vi-node/node_modules/bluebird/js/release/promise.js:559:18)
  at Promise._settlePromise0 (/opt/vi-node/node_modules/bluebird/js/release/promise.js:604:10)
  at Promise._settlePromises (/opt/vi-node/node_modules/bluebird/js/release/promise.js:683:18)
  at Promise._fulfill (/opt/vi-node/node_modules/bluebird/js/release/promise.js:628:18)
  at PromiseArray._resolve (/opt/vi-node/node_modules/bluebird/js/release/promise_array.js:125:19)
  at PromiseArray._promiseFulfilled (/opt/vi-node/node_modules/bluebird/js/release/promise_array.js:143:14)
  at Promise._settlePromise (/opt/vi-node/node_modules/bluebird/js/release/promise.js:564:26)
  at Promise._settlePromise0 (/opt/vi-node/node_modules/bluebird/js/release/promise.js:604:10)
  at Promise._settlePromises (/opt/vi-node/node_modules/bluebird/js/release/promise.js:683:18)
  at Async._drainQueue (/opt/vi-node/node_modules/bluebird/js/release/async.js:138:16)
  at Async._drainQueues (/opt/vi-node/node_modules/bluebird/js/release/async.js:148:10)
  at Immediate.Async.drainQueues [as _onImmediate] (/opt/vi-node/node_modules/bluebird/js/release/async.js:17:14)
  at processImmediate [as _immediateCallback] (timers.js:368:17)
```

**Comment by oleksiyk** [comment]
Which version of no-kafka is that?

**Comment by memelet** [comment]
no-kafka is 2.5.1. We have also reproduced using node 4.2.0 and 5.11.1. 

But we cannot reproduce when running on OSX, only Ubuntu 14.04.

**Comment by oleksiyk** [comment]
What kind of messages do you send?

**Comment by memelet** [comment]
Strings of JSON. Sometimes up to 10k json documents. We have no problem sending that size from OSX (using the same source for the data), but not on production/Ubuntu.

**Comment by memelet** [comment]
We are not batching, will try that now.

**Comment by memelet** [comment]
Just was able to send to 10k (of our records) with no problem. So maybe the size is not the problem...

**Comment by oleksiyk** [comment]
Are you using compression?

**Comment by memelet** [comment]
No ```codec: kafka.COMPRESSION_NONE``

The data looks like an array of:
```
  topic: topic
  message: {value: JSON.stringify(item)}
```

**Comment by memelet** [comment]
It's not always failing. Even with same number of messages. (We input is batched to 10k). Could it be something in our JSON?

**Comment by oleksiyk** [comment]
Try no-kafka 2.5.2

**Comment by memelet** [comment]
Will do, waiting on npm...

**Comment by oleksiyk** [comment]
both no-kafka 2.5.2 and bin-protocol 3.0.2 are already published to npm, at least staves got them OK

**Comment by memelet** [comment]
Look good. Cannot reproduce at all. Thanks!
